apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-and-mongodb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-and-mongodb
  template:
    metadata:
      labels:
        app: app-and-mongodb
    spec:
      containers:
      - name: nodejs-app
        image: gopathileha/travel:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: "mongodb://localhost:27017/travel-reservation"
        - name: PORT
          value: "3001"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "travel-reservation"