apiVersion: v1
kind: Service
metadata:
  name: leha
spec:
  type: LoadBalancer # Use ClusterIP or NodePort based on your requirements
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 31000
      protocol: TCP
  selector:
    app: travel  